// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Q664VphatC6PGb2g9_N26J4-JSObytA',
    appId: '1:206934141492:web:61c1a3263f1518a9fa7861',
    messagingSenderId: '206934141492',
    projectId: 'agro-new',
    authDomain: 'agro-new.firebaseapp.com',
    storageBucket: 'agro-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgkxMHhOshNwvxzvobXUqfdN01jrMBxqY',
    appId: '1:206934141492:android:8a6259a3bdf35c9dfa7861',
    messagingSenderId: '206934141492',
    projectId: 'agro-new',
    storageBucket: 'agro-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMlMV4jb2EI8vjI9ecOaSn0IKFzpOgTi4',
    appId: '1:206934141492:ios:2f2a370e069d10f3fa7861',
    messagingSenderId: '206934141492',
    projectId: 'agro-new',
    storageBucket: 'agro-new.appspot.com',
    iosBundleId: 'com.example.agro1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMlMV4jb2EI8vjI9ecOaSn0IKFzpOgTi4',
    appId: '1:206934141492:ios:b4e0300000abde8ffa7861',
    messagingSenderId: '206934141492',
    projectId: 'agro-new',
    storageBucket: 'agro-new.appspot.com',
    iosBundleId: 'com.example.agro1.RunnerTests',
  );
}
